# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcm_cpp <- function(texts, types, window) {
    .Call('quanteda_fcm_cpp', PACKAGE = 'quanteda', texts, types, window)
}

skipgramcpp <- function(tokens, ns, ks, delim) {
    .Call('quanteda_skipgramcpp', PACKAGE = 'quanteda', tokens, ns, ks, delim)
}

wordfishcpp <- function(wfm, dir, priors, tol, disp, dispfloor) {
    .Call('quanteda_wordfishcpp', PACKAGE = 'quanteda', wfm, dir, priors, tol, disp, dispfloor)
}

